# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('expand', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('likecount', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, max_length=256, null=True, upload_to='posts_images')),
                ('video', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
    ]
